version: "3.9"
services:
  server:
    build: ./backendpython
    ports:
    - "3001:3001"
    volumes:
    - ./backendpython:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./frontendreact
    ports:
    - "3000:3000"
    volumes:
      - ./frontendreact:/usr/src/app
    depends_on:
      - server